[package]
name = "keylogger-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
rand = "0.8"
block-modes = "0.9"
base64 = "0.22"
ctrlc = "3.4"
chrono = "0.4"  # Para timestamps en el futuro
winapi = { version = "0.3.9", features = ["winuser"] }
