[package]
name = "keylogger-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
rand = "0.8"
block-modes = "0.9"
base64 = "0.22"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader"
] }
ctrlc = "3.4"
chrono = "0.4"  # Para timestamps en el futuro